services:
  - type: web
    name: sayman-blockchain
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js --network public-testnet --mode validator
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /var/data/sayman-db
    healthCheckPath: /api/stats
    autoDeploy: true
    disk:
      name: sayman-data
      mountPath: /var/data
      sizeGB: 1

  - type: web
    name: sayman-faucet
    env: node
    region: oregon
    plan: free
    buildCommand: cd faucet && npm install
    startCommand: cd faucet && node server.js
    envVars:
      - key: FAUCET_PORT
        value: 10000
      - key: FAUCET_AMOUNT
        value: 1000
    healthCheckPath: /health
